export interface SeedInvestmentOption {
  id: string
  assetClass: string
  name: string
  ticker?: string
  description: string
  marketInfo?: string
  payoutFrequency?: string
  priceValue?: number
}

// Dados de mercado pesquisados em 20/08/2026. São aproximados, mudam diariamente
// e não são garantia de rentabilidade futura — apenas referência educacional.
export const investmentOptions: SeedInvestmentOption[] = [
  // ETFs
  {
    id: 'bova11', assetClass: 'ETFs', name: 'BOVA11', ticker: 'BOVA11',
    description: 'ETF que busca acompanhar o Ibovespa, principal índice da bolsa brasileira.',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 132.40,
  },
  {
    id: 'ivvb11', assetClass: 'ETFs', name: 'IVVB11', ticker: 'IVVB11',
    description: 'ETF que busca acompanhar o S&P 500, principal índice de ações dos EUA.',
    marketInfo: 'S&P 500 subiu ≈ +10% só no 1º semestre de 2026 (retorno total).',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 298.70,
  },
  {
    id: 'smal11', assetClass: 'ETFs', name: 'SMAL11', ticker: 'SMAL11',
    description: 'ETF que acompanha um índice de empresas brasileiras de menor capitalização (small caps).',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 96.80,
  },
  {
    id: 'divo11', assetClass: 'ETFs', name: 'DIVO11', ticker: 'DIVO11',
    description: 'ETF que acompanha um índice de empresas boas pagadoras de dividendos na B3.',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 24.15,
  },
  {
    id: 'find11', assetClass: 'ETFs', name: 'FIND11', ticker: 'FIND11',
    description: 'ETF setorial que acompanha o índice financeiro da B3, concentrado em grandes bancos e seguradoras.',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 19.35,
  },
  {
    id: 'gold11', assetClass: 'ETFs', name: 'GOLD11', ticker: 'GOLD11',
    description: 'ETF que busca acompanhar a variação do preço do ouro no mercado internacional.',
    payoutFrequency: 'Não distribui — não há renda associada ao ouro, só variação de preço.',
    priceValue: 68.90,
  },
  {
    id: 'hash11', assetClass: 'ETFs', name: 'HASH11', ticker: 'HASH11',
    description: 'ETF que acompanha um índice diversificado de criptomoedas, permitindo exposição a cripto por uma corretora de ações tradicional.',
    marketInfo: 'Fortemente correlacionado ao Bitcoin e Ethereum — alta volatilidade (ago/2026).',
    payoutFrequency: 'Não distribui — ganho vem só da valorização (ou desvalorização) da cota.',
    priceValue: 11.20,
  },
  {
    id: 'ecoo11', assetClass: 'ETFs', name: 'ECOO11', ticker: 'ECOO11',
    description: 'ETF que acompanha o Índice de Sustentabilidade Empresarial (ISE) da B3, com empresas avaliadas por critérios ESG.',
    marketInfo: 'Composição próxima do Ibovespa, mas filtrada por critérios ambientais, sociais e de governança.',
    payoutFrequency: 'Não distribui — dividendos das empresas da carteira são reinvestidos na cota.',
    priceValue: 102.50,
  },

  // Renda fixa
  {
    id: 'tesouro-selic', assetClass: 'Renda fixa', name: 'Tesouro Selic',
    description: 'Título público pós-fixado atrelado à Selic, indicado para reserva de emergência pela alta liquidez.',
    marketInfo: 'Selic atual: 14,00% a.a. (Copom, ago/2026).',
    payoutFrequency: 'Sem pagamento periódico — rende diariamente e só é recebido no resgate ou vencimento.',
  },
  {
    id: 'tesouro-ipca', assetClass: 'Renda fixa', name: 'Tesouro IPCA+',
    description: 'Título público que paga inflação (IPCA) mais uma taxa fixa, indicado para objetivos de longo prazo.',
    marketInfo: 'IPCA acumulado 12 meses: ≈ 4,44% (jul/2026), mais a taxa fixa do título.',
    payoutFrequency: 'Sem pagamento periódico (salvo a versão "com juros semestrais") — geralmente recebido só no vencimento.',
  },
  {
    id: 'cdb', assetClass: 'Renda fixa', name: 'CDB',
    description: 'Certificado de Depósito Bancário, título privado de bancos, geralmente atrelado a um percentual do CDI.',
    marketInfo: 'CDI atual ≈ 13,90% a.a.; CDBs de bancos médios oferecem ≈ 100% a 120% do CDI (ago/2026).',
    payoutFrequency: 'Sem pagamento periódico na maioria dos casos — rende no período e é recebido no vencimento ou resgate.',
  },
  {
    id: 'lci-lca', assetClass: 'Renda fixa', name: 'LCI/LCA',
    description: 'Letras de crédito imobiliário/agrícola, isentas de Imposto de Renda para pessoa física.',
    marketInfo: 'Costumam pagar 85% a 95% do CDI (≈13,90% a.a.), mas isentas de IR — rendimento líquido pode superar CDB.',
    payoutFrequency: 'Sem pagamento periódico — rendimento é recebido no vencimento ou resgate.',
  },

  // FIIs
  {
    id: 'hglg11', assetClass: 'FIIs', name: 'HGLG11', ticker: 'HGLG11',
    description: 'Fundo imobiliário de galpões logísticos.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 163.50,
  },
  {
    id: 'knri11', assetClass: 'FIIs', name: 'KNRI11', ticker: 'KNRI11',
    description: 'Fundo imobiliário híbrido, com imóveis corporativos e logísticos.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 151.20,
  },
  {
    id: 'mxrf11', assetClass: 'FIIs', name: 'MXRF11', ticker: 'MXRF11',
    description: 'Fundo imobiliário de recebíveis (papel), focado em títulos ligados ao mercado imobiliário.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 9.85,
  },
  {
    id: 'gare11', assetClass: 'FIIs', name: 'GARE11', ticker: 'GARE11',
    description: 'Fundo imobiliário da Guardian Real Estate, focado em imóveis de renda urbana (varejo e logística) alugados para grandes redes.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 8.19,
  },
  {
    id: 'xpml11', assetClass: 'FIIs', name: 'XPML11', ticker: 'XPML11',
    description: 'Fundo imobiliário de shopping centers, com participação em empreendimentos espalhados pelo Brasil.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 107.40,
  },
  {
    id: 'visc11', assetClass: 'FIIs', name: 'VISC11', ticker: 'VISC11',
    description: 'Fundo imobiliário de shopping centers, com participação em diversos empreendimentos no Brasil.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 109.90,
  },
  {
    id: 'btlg11', assetClass: 'FIIs', name: 'BTLG11', ticker: 'BTLG11',
    description: 'Fundo imobiliário de galpões logísticos e industriais, com contratos de longo prazo com grandes empresas.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 99.60,
  },
  {
    id: 'kncr11', assetClass: 'FIIs', name: 'KNCR11', ticker: 'KNCR11',
    description: 'Fundo imobiliário de recebíveis atrelado ao CDI, com baixa volatilidade de preço em relação a outros FIIs.',
    payoutFrequency: 'Mensal (como a maioria dos FIIs).',
    priceValue: 98.70,
  },

  // Fundos Multimercado
  {
    id: 'multi-macro', assetClass: 'Fundos Multimercado', name: 'Fundo Multimercado Macro',
    description: 'Aposta em cenários econômicos amplos, combinando juros, câmbio e bolsa.',
    marketInfo: 'Retorno varia muito de fundo para fundo — não há uma taxa de mercado única para comparar.',
    payoutFrequency: 'Geralmente não distribui — ganho vem da valorização da cota (fundo de acumulação).',
  },
  {
    id: 'multi-long-short', assetClass: 'Fundos Multimercado', name: 'Fundo Multimercado Long Short',
    description: 'Compra e vende ações simultaneamente buscando lucrar com a diferença entre elas, com menor exposição ao mercado.',
    marketInfo: 'Retorno varia muito de fundo para fundo — não há uma taxa de mercado única para comparar.',
    payoutFrequency: 'Geralmente não distribui — ganho vem da valorização da cota (fundo de acumulação).',
  },
  {
    id: 'multi-livre', assetClass: 'Fundos Multimercado', name: 'Fundo Multimercado Livre',
    description: 'Liberdade para alocar em diversas classes de ativos conforme a visão do gestor.',
    marketInfo: 'Retorno varia muito de fundo para fundo — não há uma taxa de mercado única para comparar.',
    payoutFrequency: 'Geralmente não distribui — ganho vem da valorização da cota (fundo de acumulação).',
  },

  // Criptomoedas
  {
    id: 'bitcoin', assetClass: 'Criptomoedas', name: 'Bitcoin', ticker: 'BTC',
    description: 'Criptomoeda pioneira e mais valorizada do mercado, usada como reserva de valor digital.',
    marketInfo: '≈ US$ 64.900 (19/ago/2026), em mercado de baixa desde fev/2026 — alta volatilidade.',
    payoutFrequency: 'Não paga nada — ganho vem só da valorização (ou desvalorização) do preço.',
  },
  {
    id: 'ethereum', assetClass: 'Criptomoedas', name: 'Ethereum', ticker: 'ETH',
    description: 'Segunda maior criptomoeda, base de contratos inteligentes e aplicações descentralizadas.',
    marketInfo: '≈ US$ 1.936 (19/ago/2026), também em mercado de baixa — alta volatilidade.',
    payoutFrequency: 'Não paga nada por padrão — ganho vem da valorização (staking é uma exceção não coberta aqui).',
  },
  {
    id: 'stablecoin', assetClass: 'Criptomoedas', name: 'Stablecoin (USDT/USDC)',
    description: 'Criptomoedas atreladas ao dólar, usadas para reduzir a volatilidade dentro do mercado cripto.',
    marketInfo: '≈ US$ 1,00 por definição (paridade com o dólar) — não é feita para valorizar.',
    payoutFrequency: 'Não paga nada — não é feita para gerar renda, só para preservar valor em dólar.',
  },
  {
    id: 'solana', assetClass: 'Criptomoedas', name: 'Solana', ticker: 'SOL',
    description: 'Blockchain conhecida pela alta velocidade e baixo custo de transação, usada para contratos inteligentes e aplicações descentralizadas.',
    marketInfo: '≈ US$ 148 (19/ago/2026) — alta volatilidade, historicamente maior que Bitcoin e Ethereum.',
    payoutFrequency: 'Não paga nada por padrão — ganho vem da valorização (staking é uma exceção não coberta aqui).',
  },
  {
    id: 'bnb', assetClass: 'Criptomoedas', name: 'BNB', ticker: 'BNB',
    description: 'Criptomoeda da Binance, uma das maiores corretoras de criptomoedas do mundo, usada para pagar taxas e outras funções dentro do seu ecossistema.',
    marketInfo: '≈ US$ 572 (19/ago/2026) — alta volatilidade, ligada ao desempenho da própria Binance.',
    payoutFrequency: 'Não paga nada — ganho vem só da valorização (ou desvalorização) do preço.',
  },
  {
    id: 'xrp', assetClass: 'Criptomoedas', name: 'XRP', ticker: 'XRP',
    description: 'Criptomoeda voltada para pagamentos e transferências internacionais rápidas entre instituições financeiras.',
    marketInfo: '≈ US$ 0,58 (19/ago/2026) — alta volatilidade, historicamente ligada a decisões regulatórias.',
    payoutFrequency: 'Não paga nada — ganho vem só da valorização (ou desvalorização) do preço.',
  },
]

export interface SeedCompany {
  id: string
  name: string
  ticker: string
  sector: string
  whatItDoes: string
  howItMakesMoney: string
  revenue: string
  profit: string
  margin: string
  roe: string
  debt: string
  cashFlow: string
  pl: string
  pvp: string
  dividendYield: string
  growth: string
  risks: string[]
  outlook: string
  positives: string[]
  attention: string[]
  dangers: string[]
  qualitySummary: string
  priceSummary: string
  priceApprox?: string
  priceValue?: number
  payoutFrequency?: string
  // Dividend yield dos últimos 12 meses, pesquisado manualmente (statusinvest.com.br /
  // investidor10.com.br, cruzado entre as duas fontes) para os tickers em que a brapi.dev
  // não libera o módulo de dividendos no plano gratuito. dividendReferenceMonth marca até
  // quando essa pesquisa é válida — sem calendário real de pagamento, por isso nunca é
  // somado ao "Proventos esperados" (só ações com nextPaymentDate real entram nessa soma).
  dividendYieldValue?: number
  dividendReferenceMonth?: string
}

// Preço e dividend yield pesquisados em 19-21/ago/2026. São aproximados, mudam
// diariamente e rentabilidade passada não garante rentabilidade futura.
export const companies: SeedCompany[] = [
  {
    id: 'itau',
    name: 'Itaú Unibanco',
    ticker: 'ITUB4',
    sector: 'Bancos',
    whatItDoes: 'Maior banco privado da América Latina, oferecendo crédito, cartões, seguros, investimentos e serviços financeiros para pessoas físicas e empresas.',
    howItMakesMoney: 'Cobra juros sobre empréstimos e financiamentos, tarifas de serviços, e ganha com a diferença entre o que paga para captar dinheiro e o que cobra para emprestá-lo (spread bancário).',
    revenue: 'Receita de serviços e margem financeira em crescimento consistente nos últimos anos (exemplo educacional).',
    profit: 'Lucro líquido recorrente na casa de dezenas de bilhões de reais por ano (exemplo educacional).',
    margin: 'Margem financeira historicamente saudável para o setor bancário (exemplo educacional).',
    roe: 'ROE historicamente próximo de 20%, um dos mais altos entre bancos brasileiros (exemplo educacional).',
    debt: 'Estrutura de capital regulada pelo Banco Central; não se analisa dívida como em empresas comuns, e sim índices de capital e inadimplência.',
    cashFlow: 'Geração de caixa operacional robusta, típica de bancos de grande porte (exemplo educacional).',
    pl: 'P/L historicamente na faixa de 7x a 10x (exemplo educacional).',
    pvp: 'P/VP historicamente próximo de 1,5x a 2x (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 8,3% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 38,35 (19/ago/2026)',
    priceValue: 38.35,
    payoutFrequency: 'Mensal — um dos poucos bancos que pagam todo mês, com complementos semestrais.',
    growth: 'Crescimento moderado, puxado por expansão da carteira de crédito e serviços digitais.',
    risks: ['Inadimplência em cenários de juros altos', 'Concorrência de bancos digitais', 'Regulação do setor financeiro', 'Ciclos econômicos'],
    outlook: 'Perspectivas ligadas ao crescimento do crédito no Brasil e à digitalização dos serviços financeiros.',
    positives: ['Rentabilidade historicamente alta (ROE)', 'Marca consolidada e grande base de clientes', 'Diversificação de receitas'],
    attention: ['Sensível ao ciclo de juros e crédito', 'Múltiplos podem variar bastante com o humor do mercado'],
    dangers: ['Forte concorrência de fintechs e bancos digitais', 'Inadimplência em cenários de recessão'],
    qualitySummary: 'Empresa historicamente considerada de alta qualidade dentro do setor bancário, com rentabilidade consistente.',
    priceSummary: 'O preço deve ser avaliado em relação ao ROE entregue e ao ciclo de crédito e juros do momento.',
  },
  {
    id: 'petrobras',
    name: 'Petrobras',
    ticker: 'PETR4',
    sector: 'Petróleo e gás',
    whatItDoes: 'Estatal brasileira que atua na exploração, produção, refino e distribuição de petróleo, gás natural e derivados.',
    howItMakesMoney: 'Vende petróleo, gás e derivados (como gasolina e diesel) no mercado interno e externo, com receita fortemente ligada ao preço internacional do petróleo.',
    revenue: 'Receita altamente sensível ao preço do barril de petróleo e à taxa de câmbio (exemplo educacional).',
    profit: 'Lucro historicamente volátil, acompanhando o ciclo de preços das commodities (exemplo educacional).',
    margin: 'Margens historicamente elevadas em ciclos de petróleo em alta, e comprimidas em ciclos de baixa.',
    roe: 'ROE historicamente volátil, variando fortemente entre ciclos de commodities (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, com esforço de redução de dívida líquida/EBITDA nos últimos anos (exemplo educacional).',
    cashFlow: 'Forte geração de caixa operacional em ciclos de petróleo em alta.',
    pl: 'P/L historicamente baixo em comparação a outros setores, refletindo o risco político e a volatilidade do setor (exemplo educacional).',
    pvp: 'P/VP historicamente abaixo de 1,5x (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 7,3% ao ano nos últimos 12 meses (pesquisado em jul/2026), historicamente entre os mais altos da bolsa.',
    priceApprox: 'R$ 41,65 (21/jul/2026)',
    priceValue: 41.65,
    payoutFrequency: 'Trimestral (política da empresa), podendo ter distribuições extras em anos de caixa forte.',
    growth: 'Crescimento ligado a novos poços do pré-sal e à evolução da produção, mais do que à expansão de mercado.',
    risks: ['Risco político (empresa estatal)', 'Volatilidade do preço do petróleo', 'Câmbio', 'Mudanças na política de preços e dividendos'],
    outlook: 'Perspectivas ligadas à produção do pré-sal, preço internacional do petróleo e transição energética de longo prazo.',
    positives: ['Grandes reservas no pré-sal', 'Custo de extração competitivo em parte dos ativos', 'Histórico de bons dividendos em ciclos de alta'],
    attention: ['Política de preços pode mudar por decisão do governo', 'Alta volatilidade de resultados'],
    dangers: ['Interferência política em decisões estratégicas', 'Dependência do preço internacional do petróleo', 'Transição energética de longo prazo'],
    qualitySummary: 'Ativos de classe mundial no pré-sal, mas com risco de governança por ser uma estatal.',
    priceSummary: 'Costuma negociar com desconto em relação a pares privados, refletindo o risco político.',
  },
  {
    id: 'vale',
    name: 'Vale',
    ticker: 'VALE3',
    sector: 'Mineração',
    whatItDoes: 'Uma das maiores mineradoras do mundo, com foco na extração e venda de minério de ferro, além de níquel e cobre.',
    howItMakesMoney: 'Vende minério de ferro e outros metais principalmente para siderúrgicas globais, com forte dependência da demanda chinesa.',
    revenue: 'Receita fortemente correlacionada ao preço internacional do minério de ferro (exemplo educacional).',
    profit: 'Lucro historicamente volátil, seguindo o ciclo de preços das commodities (exemplo educacional).',
    margin: 'Margens historicamente elevadas por ter custo de produção competitivo globalmente.',
    roe: 'ROE historicamente volátil, atingindo picos altos em ciclos de minério em alta (exemplo educacional).',
    debt: 'Dívida líquida historicamente controlada, com política de disciplina de capital nos últimos anos (exemplo educacional).',
    cashFlow: 'Forte geração de caixa em ciclos de minério em alta, usada para dividendos e recompras.',
    pl: 'P/L ≈ 29,3 (pesquisado em ago/2026) — acima da média histórica, também reflete a forte alta da cotação em 12 meses (≈+41%).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 7,8% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 71,55 (ago/2026)',
    priceValue: 71.55,
    payoutFrequency: 'Semestral (pagamentos regulares em março e setembro), mais eventuais extraordinários.',
    growth: 'Crescimento ligado a expansão de produção e não necessariamente a novos mercados.',
    risks: ['Preço do minério de ferro', 'Dependência da economia chinesa', 'Riscos ambientais e de segurança operacional', 'Custos regulatórios após acidentes passados'],
    outlook: 'Perspectivas ligadas à demanda global por aço, infraestrutura chinesa e transição para minérios de maior qualidade.',
    positives: ['Baixo custo de produção global', 'Grandes reservas de minério de alta qualidade', 'Forte geração de caixa em ciclos favoráveis'],
    attention: ['Forte dependência de um único comprador relevante (China)', 'Resultados cíclicos e voláteis'],
    dangers: ['Riscos ambientais e de segurança em operações de mineração', 'Desaceleração da economia chinesa'],
    qualitySummary: 'Ativo de baixo custo e classe mundial, mas com resultados historicamente cíclicos.',
    priceSummary: 'Múltiplos tendem a parecer baratos no topo do ciclo e caros no fundo do ciclo — é preciso olhar além do P/L momentâneo.',
  },
  {
    id: 'weg',
    name: 'WEG',
    ticker: 'WEGE3',
    sector: 'Bens de capital / Indústria',
    whatItDoes: 'Fabricante brasileira de motores elétricos, geradores, transformadores e equipamentos industriais, com forte presença internacional.',
    howItMakesMoney: 'Vende produtos industriais e soluções de energia para clientes no Brasil e no exterior, incluindo mercados de energia renovável.',
    revenue: 'Histórico de crescimento consistente de receita, impulsionado por exportações e diversificação de produtos (exemplo educacional).',
    profit: 'Lucro em crescimento consistente ao longo dos anos (exemplo educacional).',
    margin: 'Margens historicamente elevadas e estáveis para o setor industrial (exemplo educacional).',
    roe: 'ROE historicamente elevado e consistente, um destaque entre empresas industriais brasileiras (exemplo educacional).',
    debt: 'Endividamento historicamente baixo e controlado (exemplo educacional).',
    cashFlow: 'Boa geração de caixa operacional, sustentando investimentos e dividendos.',
    pl: 'P/L historicamente elevado em relação à média do mercado, refletindo a percepção de qualidade da empresa (exemplo educacional).',
    pvp: 'P/VP historicamente alto, também refletindo o prêmio de qualidade (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 2,4% ao ano nos últimos 12 meses (pesquisado em ago/2026) — moderado, coerente com reinvestimento em crescimento.',
    priceApprox: 'R$ 48,44 (ago/2026)',
    priceValue: 48.44,
    dividendYieldValue: 2.44,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Semestral (historicamente em março e agosto), com eventuais pagamentos extras.',
    growth: 'Crescimento consistente ao longo de décadas, com forte disciplina de execução.',
    risks: ['Múltiplos historicamente elevados (valuation exigente)', 'Câmbio (parte relevante da receita vem de exportação)', 'Ciclo industrial global'],
    outlook: 'Perspectivas ligadas à eletrificação industrial, energia renovável e expansão internacional.',
    positives: ['Histórico consistente de crescimento e execução', 'Alta rentabilidade (ROE)', 'Baixo endividamento'],
    attention: ['Valuation historicamente exigente (P/L e P/VP altos)', 'Parte relevante do resultado depende do câmbio'],
    dangers: ['Pagar caro demais por uma empresa boa é, ainda assim, um risco de valuation'],
    qualitySummary: 'Uma das empresas industriais mais bem avaliadas da bolsa brasileira, com histórico consistente de qualidade.',
    priceSummary: 'Costuma negociar com múltiplos mais altos que a média do mercado, refletindo a qualidade percebida do negócio.',
  },
  {
    id: 'bb',
    name: 'Banco do Brasil',
    ticker: 'BBAS3',
    sector: 'Bancos',
    whatItDoes: 'Banco público federal, um dos maiores do país, com forte atuação em crédito rural e correspondente bancário do governo.',
    howItMakesMoney: 'Assim como outros bancos, ganha com juros sobre crédito, tarifas de serviços e spread bancário — com forte exposição ao agronegócio.',
    revenue: 'Receita de serviços e margem financeira ligadas fortemente ao crédito rural e ao varejo bancário (exemplo educacional).',
    profit: 'Lucro historicamente robusto, mas historicamente com múltiplos mais baixos que bancos privados por ser estatal (exemplo educacional).',
    margin: 'Margem financeira em linha com a média do setor bancário.',
    roe: 'ROE historicamente competitivo com bancos privados em anos recentes (exemplo educacional).',
    debt: 'Estrutura de capital regulada pelo Banco Central, como os demais bancos.',
    cashFlow: 'Geração de caixa operacional robusta, típica de bancos de grande porte.',
    pl: 'P/L ≈ 8,55 (pesquisado em ago/2026), descontado frente aos bancos privados.',
    pvp: 'P/VP historicamente abaixo de 1x em vários períodos (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 3,0% ao ano nos últimos 12 meses (ago/2026) — caiu de patamares mais altos após corte no payout.',
    priceApprox: 'R$ 18,12 (ago/2026)',
    priceValue: 18.12,
    dividendYieldValue: 3.04,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral (JCP antecipado por trimestre) mais complemento no fim do ano.',
    growth: 'Crescimento ligado à expansão do crédito, especialmente rural e para pequenas empresas.',
    risks: ['Risco político (empresa estatal)', 'Exposição concentrada ao agronegócio', 'Inadimplência em cenários de juros altos'],
    outlook: 'Perspectivas ligadas ao crédito rural, à digitalização e à política de dividendos do governo.',
    positives: ['Dividend Yield historicamente atrativo', 'Forte presença no agronegócio', 'Múltiplos historicamente descontados frente a pares privados'],
    attention: ['Decisões podem sofrer influência política', 'Depende fortemente da saúde do agronegócio'],
    dangers: ['Interferência do governo em decisões estratégicas ou de dividendos'],
    qualitySummary: 'Banco sólido, mas historicamente negociado com desconto frente a bancos privados por conta do risco de governança estatal.',
    priceSummary: 'Costuma negociar com múltiplos mais baixos que bancos privados equivalentes.',
  },
  {
    id: 'engie',
    name: 'Engie Brasil',
    ticker: 'EGIE3',
    sector: 'Energia elétrica',
    whatItDoes: 'Geradora de energia elétrica no Brasil, com forte presença em fontes renováveis como hidrelétricas, eólicas e solares.',
    howItMakesMoney: 'Vende energia elétrica através de contratos de longo prazo com distribuidoras e grandes consumidores.',
    revenue: 'Receita previsível, sustentada por contratos de venda de energia de longo prazo (exemplo educacional).',
    profit: 'Lucro estável e previsível, típico de empresas do setor elétrico (exemplo educacional).',
    margin: 'Margens historicamente elevadas e estáveis (exemplo educacional).',
    roe: 'ROE historicamente sólido para o setor de utilities (exemplo educacional).',
    debt: 'Endividamento moderado, usado para financiar expansão de capacidade de geração (exemplo educacional).',
    cashFlow: 'Geração de caixa previsível, sustentando uma política de dividendos consistente.',
    pl: 'P/L historicamente moderado, condizente com um setor de baixo crescimento e alta previsibilidade (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 7,3% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 27,61 (ago/2026)',
    priceValue: 27.61,
    dividendYieldValue: 7.32,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Cerca de 3x ao ano (historicamente fevereiro, maio e dezembro).',
    growth: 'Crescimento moderado, ligado a novos projetos de geração e leilões de energia.',
    risks: ['Regulação do setor elétrico', 'Renovação de concessões', 'Condições hidrológicas (regime de chuvas)'],
    outlook: 'Perspectivas ligadas à expansão de energias renováveis e à demanda futura de energia no Brasil.',
    positives: ['Receita previsível via contratos de longo prazo', 'Bom histórico de dividendos', 'Matriz predominantemente renovável'],
    attention: ['Crescimento historicamente mais lento que setores cíclicos', 'Depende de leilões e renovação de concessões'],
    dangers: ['Mudanças regulatórias podem afetar contratos e tarifas'],
    qualitySummary: 'Empresa historicamente considerada defensiva, com receitas previsíveis e bons dividendos.',
    priceSummary: 'Costuma ser avaliada mais pelo Dividend Yield e previsibilidade do que por potencial de crescimento acelerado.',
  },
  {
    id: 'taesa',
    name: 'Taesa',
    ticker: 'TAEE11',
    sector: 'Energia elétrica (transmissão)',
    whatItDoes: 'Empresa de transmissão de energia elétrica, responsável por transportar energia entre geradoras e distribuidoras através de linhas de alta tensão.',
    howItMakesMoney: 'Recebe uma receita fixa anual (RAP — Receita Anual Permitida), definida em contratos regulados, pela disponibilização das linhas de transmissão.',
    revenue: 'Receita previsível e contratada, reajustada anualmente por índices de inflação (exemplo educacional).',
    profit: 'Lucro estável, refletindo a natureza regulada e previsível do negócio (exemplo educacional).',
    margin: 'Margens historicamente muito elevadas, típicas de negócios de transmissão de energia (exemplo educacional).',
    roe: 'ROE historicamente elevado dentro do setor de utilities (exemplo educacional).',
    debt: 'Endividamento moderado a alto, comum no setor por ser intensivo em capital, mas com receita previsível para sustentá-lo (exemplo educacional).',
    cashFlow: 'Geração de caixa previsível, sustentando uma das maiores políticas de distribuição de dividendos da bolsa.',
    pl: 'P/L historicamente moderado (exemplo educacional).',
    pvp: 'P/VP historicamente moderado a elevado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 8,0% ao ano nos últimos 12 meses (ago/2026), dentro da faixa histórica de 8% a 12%.',
    priceApprox: 'R$ 37,30 (ago/2026)',
    priceValue: 37.30,
    dividendYieldValue: 8.03,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Cerca de 4x ao ano (historicamente janeiro, maio, agosto e novembro).',
    growth: 'Crescimento ligado à conquista de novos leilões de linhas de transmissão.',
    risks: ['Regulação do setor elétrico', 'Dependência de novos leilões para crescer', 'Endividamento para financiar novos ativos'],
    outlook: 'Perspectivas ligadas a novos leilões de transmissão e à expansão da malha elétrica brasileira.',
    positives: ['Receita altamente previsível e contratada', 'Histórico consistente de dividendos elevados', 'Margens muito altas'],
    attention: ['Crescimento depende de vencer novos leilões', 'Uso de dívida para financiar expansão'],
    dangers: ['Mudanças regulatórias no setor de transmissão'],
    qualitySummary: 'Negócio previsível e defensivo, com uma das maiores distribuições de dividendos da bolsa.',
    priceSummary: 'Costuma ser avaliada principalmente pelo Dividend Yield frente a outras opções de renda.',
  },
  {
    id: 'localiza',
    name: 'Localiza',
    ticker: 'RENT3',
    sector: 'Aluguel de veículos',
    whatItDoes: 'Maior empresa de aluguel de carros e gestão de frotas da América Latina.',
    howItMakesMoney: 'Compra veículos, aluga para pessoas físicas e empresas, e depois revende os carros usados de sua frota, lucrando com aluguel e com a diferença de compra e venda.',
    revenue: 'Receita em crescimento consistente, impulsionada pela expansão da frota e de novas unidades (exemplo educacional).',
    profit: 'Lucro sensível ao custo dos veículos e às taxas de juros usadas para financiar a frota (exemplo educacional).',
    margin: 'Margens historicamente saudáveis, mas sensíveis ao preço de compra e revenda de veículos.',
    roe: 'ROE historicamente elevado em períodos favoráveis do ciclo de crédito e preço de carros (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do modelo de negócio intensivo em capital (financiamento da frota) (exemplo educacional).',
    cashFlow: 'Fluxo de caixa fortemente influenciado pelo ciclo de compra e venda de veículos.',
    pl: 'P/L ≈ 19,4 (pesquisado em ago/2026), refletindo a expectativa de crescimento do setor.',
    pvp: 'P/VP historicamente elevado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 6,4% ao ano nos últimos 12 meses (ago/2026).',
    priceApprox: 'R$ 33,40 (ago/2026)',
    priceValue: 33.40,
    dividendYieldValue: 6.44,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Cerca de 4x ao ano (aproximadamente trimestral, via JCP).',
    growth: 'Crescimento historicamente forte, com expansão de frota e consolidação do setor.',
    risks: ['Alto endividamento para financiar a frota', 'Sensibilidade a juros', 'Preço de veículos novos e usados'],
    outlook: 'Perspectivas ligadas à penetração de aluguel de carros e gestão de frotas no Brasil.',
    positives: ['Líder de mercado com escala relevante', 'Histórico de crescimento consistente', 'Modelo de negócio testado ao longo de décadas'],
    attention: ['Alto endividamento é inerente ao modelo de negócio', 'Sensível ao custo de capital (juros)'],
    dangers: ['Ciclos de juros altos encarecem o financiamento da frota', 'Queda no valor de revenda dos veículos usados'],
    qualitySummary: 'Líder consolidado em um setor de barreiras de entrada relevantes, mas com uso intenso de dívida.',
    priceSummary: 'Historicamente negociada com múltiplos mais altos, refletindo a expectativa de crescimento.',
  },
  {
    id: 'b3',
    name: 'B3',
    ticker: 'B3SA3',
    sector: 'Infraestrutura de mercado financeiro',
    whatItDoes: 'Administra a bolsa de valores brasileira e a infraestrutura de negociação, compensação e liquidação de ativos financeiros no Brasil.',
    howItMakesMoney: 'Cobra taxas sobre negociação, listagem e liquidação de ações, derivativos e outros ativos financeiros negociados na bolsa.',
    revenue: 'Receita ligada ao volume de negociação na bolsa brasileira, com boa diversificação entre renda variável e outros produtos (exemplo educacional).',
    profit: 'Lucro historicamente elevado, com margens muito altas por ser um negócio de infraestrutura com pouca necessidade de capital físico adicional (exemplo educacional).',
    margin: 'Margens historicamente entre as mais altas da bolsa brasileira (exemplo educacional).',
    roe: 'ROE historicamente elevado (exemplo educacional).',
    debt: 'Endividamento historicamente baixo a moderado (exemplo educacional).',
    cashFlow: 'Forte geração de caixa, típica de negócios de infraestrutura de mercado com baixa necessidade de reinvestimento.',
    pl: 'P/L ≈ 15,55 (pesquisado em ago/2026), refletindo a qualidade do negócio.',
    pvp: 'P/VP historicamente elevado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 4,2% ao ano nos últimos 12 meses (ago/2026), combinado com recompras de ações.',
    priceApprox: 'R$ 14,95 (ago/2026)',
    priceValue: 14.95,
    dividendYieldValue: 4.22,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral (janeiro, abril, julho e outubro, aproximadamente).',
    growth: 'Crescimento ligado ao aumento do volume negociado na bolsa e à entrada de novos investidores no mercado de capitais brasileiro.',
    risks: ['Depende do volume de negociação do mercado', 'Concorrência de novas infraestruturas de negociação', 'Regulação do mercado de capitais'],
    outlook: 'Perspectivas ligadas ao crescimento do número de investidores pessoa física e ao desenvolvimento do mercado de capitais brasileiro.',
    positives: ['Negócio de infraestrutura com poucas alternativas concorrentes', 'Margens muito altas', 'Baixa necessidade de capital para crescer'],
    attention: ['Receita varia com o volume de negociação, que é cíclico', 'Sensível ao humor do mercado acionário como um todo'],
    dangers: ['Mudanças regulatórias que aumentem a concorrência na infraestrutura de negociação'],
    qualitySummary: 'Negócio de alta qualidade, com características de monopólio natural na infraestrutura de negociação brasileira.',
    priceSummary: 'Tende a ser avaliada pela qualidade do negócio e pelo potencial de crescimento do mercado de capitais no Brasil.',
  },
  {
    id: 'ambev',
    name: 'Ambev',
    ticker: 'ABEV3',
    sector: 'Bebidas',
    whatItDoes: 'Maior cervejaria da América Latina, dona de marcas como Skol, Brahma e Antarctica, além de refrigerantes e outras bebidas.',
    howItMakesMoney: 'Fabrica e vende cerveja, refrigerantes e outras bebidas no Brasil e em outros países da América Latina.',
    revenue: 'Receita historicamente estável, impulsionada por reajustes de preço e volume de vendas (exemplo educacional).',
    profit: 'Lucro historicamente sólido, com margens elevadas típicas do setor de bebidas (exemplo educacional).',
    margin: 'Margens historicamente altas, entre as melhores do setor de consumo (exemplo educacional).',
    roe: 'ROE historicamente moderado a elevado, variando com o custo de commodities usadas na produção (exemplo educacional).',
    debt: 'Endividamento historicamente baixo, com balanço considerado conservador (exemplo educacional).',
    cashFlow: 'Forte geração de caixa, típica de empresas de bens de consumo com marcas consolidadas.',
    pl: 'P/L historicamente moderado, refletindo um negócio maduro e de baixo crescimento (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 7,9% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 12,80 (ago/2026)',
    priceValue: 12.80,
    dividendYieldValue: 7.88,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral, com complementos ao longo do ano.',
    growth: 'Crescimento moderado, ligado ao consumo doméstico e à expansão em outros países latino-americanos.',
    risks: ['Custo de commodities (cevada, alumínio, açúcar)', 'Câmbio (parte relevante do resultado vem de fora do Brasil)', 'Mudanças em hábitos de consumo'],
    outlook: 'Perspectivas ligadas ao consumo doméstico, à premiunização do portfólio e à diversificação para além da cerveja.',
    positives: ['Marcas fortes e consolidadas', 'Grande escala de produção e distribuição', 'Geração de caixa consistente'],
    attention: ['Crescimento historicamente baixo em volume no mercado brasileiro', 'Sensível ao custo de matérias-primas'],
    dangers: ['Mudança de hábitos de consumo (bebidas alcoólicas em queda em alguns mercados)', 'Concorrência de cervejarias artesanais e outras bebidas'],
    qualitySummary: 'Empresa historicamente considerada de alta qualidade, com marcas fortes e geração de caixa consistente.',
    priceSummary: 'Costuma negociar com múltiplos moderados, refletindo o baixo crescimento do mercado de cerveja no Brasil.',
  },
  {
    id: 'bradesco',
    name: 'Bradesco',
    ticker: 'BBDC4',
    sector: 'Bancos',
    whatItDoes: 'Um dos maiores bancos privados do Brasil, com atuação em crédito, seguros, cartões, investimentos e previdência.',
    howItMakesMoney: 'Ganha com juros sobre crédito, tarifas de serviços, spread bancário e uma grande operação de seguros (Bradesco Seguros).',
    revenue: 'Receita de serviços e margem financeira ligadas ao crédito e à grande base de correntistas (exemplo educacional).',
    profit: 'Lucro historicamente relevante, mas com rentabilidade abaixo dos pares nos últimos anos (exemplo educacional).',
    margin: 'Margem financeira em recuperação após período de maior inadimplência (exemplo educacional).',
    roe: 'ROE historicamente mais baixo que Itaú nos últimos anos, mas em recuperação (exemplo educacional).',
    debt: 'Estrutura de capital regulada pelo Banco Central, como os demais bancos.',
    cashFlow: 'Geração de caixa operacional robusta, típica de bancos de grande porte.',
    pl: 'P/L historicamente na faixa de 8x a 11x (exemplo educacional).',
    pvp: 'P/VP historicamente entre 1x e 1,5x (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 9,9% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 16,20 (ago/2026)',
    priceValue: 16.20,
    dividendYieldValue: 9.85,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Mensal, com complementos ao longo do ano.',
    growth: 'Crescimento ligado à recuperação da rentabilidade e à expansão do crédito e dos seguros.',
    risks: ['Inadimplência em cenários de juros altos', 'Concorrência de bancos digitais', 'Execução da recuperação de rentabilidade'],
    outlook: 'Perspectivas ligadas à melhora do ROE, ao crescimento do crédito e à forte operação de seguros.',
    positives: ['Grande base de clientes e agências', 'Forte operação de seguros', 'Marca consolidada'],
    attention: ['Rentabilidade historicamente abaixo de bancos privados concorrentes', 'Processo de recuperação ainda em andamento'],
    dangers: ['Concorrência de fintechs e bancos digitais', 'Inadimplência em cenários de recessão'],
    qualitySummary: 'Banco tradicional e consolidado, em processo de recuperação de rentabilidade frente a concorrentes.',
    priceSummary: 'Historicamente negociado com desconto frente ao Itaú, refletindo a diferença de rentabilidade.',
  },
  {
    id: 'santander-br',
    name: 'Santander Brasil',
    ticker: 'SANB11',
    sector: 'Bancos',
    whatItDoes: 'Subsidiária brasileira do banco espanhol Santander, um dos maiores bancos privados do país.',
    howItMakesMoney: 'Ganha com juros sobre crédito, tarifas de serviços e spread bancário, com forte atuação em financiamento de veículos.',
    revenue: 'Receita de serviços e margem financeira ligadas ao crédito, especialmente financiamento de veículos (exemplo educacional).',
    profit: 'Lucro historicamente relevante, sensível ao ciclo de crédito e inadimplência (exemplo educacional).',
    margin: 'Margem financeira historicamente competitiva com os demais grandes bancos (exemplo educacional).',
    roe: 'ROE historicamente volátil, impactado por ciclos de inadimplência em crédito de veículos (exemplo educacional).',
    debt: 'Estrutura de capital regulada pelo Banco Central, como os demais bancos.',
    cashFlow: 'Geração de caixa operacional robusta, típica de bancos de grande porte.',
    pl: 'P/L historicamente na faixa de 8x a 10x (exemplo educacional).',
    pvp: 'P/VP historicamente próximo de 1,2x a 1,5x (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 7,8% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 28,50 (ago/2026)',
    priceValue: 28.50,
    dividendYieldValue: 7.83,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Mensal, com complementos ao longo do ano.',
    growth: 'Crescimento ligado à expansão do crédito, especialmente financiamento de veículos e crédito consignado.',
    risks: ['Inadimplência em crédito de veículos', 'Concorrência de bancos digitais', 'Ciclos econômicos'],
    outlook: 'Perspectivas ligadas à recuperação da qualidade da carteira de crédito e ao crescimento do crédito consignado.',
    positives: ['Forte presença em financiamento de veículos', 'Marca internacional consolidada', 'Diversificação de receitas'],
    attention: ['Historicamente mais exposto a crédito de maior risco (veículos)', 'Rentabilidade sensível ao ciclo de crédito'],
    dangers: ['Alta inadimplência em cenários de juros altos ou desemprego'],
    qualitySummary: 'Banco sólido, com forte presença em financiamento de veículos, mas historicamente mais sensível ao ciclo de crédito.',
    priceSummary: 'Múltiplos costumam refletir o risco um pouco maior da carteira de crédito frente a outros grandes bancos.',
  },
  {
    id: 'magalu',
    name: 'Magazine Luiza',
    ticker: 'MGLU3',
    sector: 'Varejo',
    whatItDoes: 'Uma das maiores redes de varejo do Brasil, com lojas físicas, e-commerce e marketplace de produtos diversos.',
    howItMakesMoney: 'Vende produtos próprios e de terceiros (marketplace), lucrando com a margem das vendas e com comissões de vendedores parceiros.',
    revenue: 'Receita fortemente ligada ao consumo das famílias e ao desempenho do e-commerce brasileiro (exemplo educacional).',
    profit: 'Lucro historicamente pressionado por juros altos e forte concorrência no e-commerce (exemplo educacional).',
    margin: 'Margens historicamente apertadas, típicas do varejo de eletrônicos e eletrodomésticos (exemplo educacional).',
    roe: 'ROE historicamente baixo nos últimos anos, refletindo o período de dificuldade do setor (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, ampliado durante os investimentos em logística e tecnologia (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível ao ciclo de vendas e ao nível de estoque.',
    pl: 'P/L historicamente muito variável, incluindo períodos de prejuízo (exemplo educacional).',
    pvp: 'P/VP historicamente baixo em períodos de maior pessimismo com o setor (exemplo educacional).',
    dividendYield: 'Dividend Yield historicamente baixo ou nulo, priorizando reinvestimento e redução de dívida.',
    priceApprox: 'R$ 9,40 (ago/2026)',
    priceValue: 9.40,
    payoutFrequency: 'Irregular — histórico de pouca ou nenhuma distribuição nos últimos anos.',
    growth: 'Crescimento ligado à expansão do marketplace e à recuperação da rentabilidade após o ciclo de juros altos.',
    risks: ['Alto endividamento', 'Forte concorrência no e-commerce (incluindo players internacionais)', 'Sensibilidade a juros e consumo das famílias'],
    outlook: 'Perspectivas ligadas à consolidação do marketplace e à melhora da rentabilidade operacional.',
    positives: ['Forte marca e infraestrutura logística construída ao longo dos anos', 'Marketplace em crescimento', 'Presença digital consolidada'],
    attention: ['Endividamento ainda elevado', 'Rentabilidade historicamente instável'],
    dangers: ['Concorrência agressiva de players internacionais de e-commerce', 'Sensibilidade a juros altos, que encarecem tanto a dívida quanto o consumo'],
    qualitySummary: 'Marca forte no varejo brasileiro, mas com histórico recente de rentabilidade instável e alavancagem elevada.',
    priceSummary: 'Historicamente muito volátil, com múltiplos sensíveis a expectativas de recuperação da rentabilidade.',
  },
  {
    id: 'suzano',
    name: 'Suzano',
    ticker: 'SUZB3',
    sector: 'Papel e celulose',
    whatItDoes: 'Uma das maiores produtoras de celulose e papel do mundo, com florestas próprias de eucalipto no Brasil.',
    howItMakesMoney: 'Vende celulose e papel para clientes no Brasil e no exterior, com receita fortemente ligada ao preço internacional da celulose e ao câmbio.',
    revenue: 'Receita fortemente exposta ao dólar, já que boa parte das vendas é exportada (exemplo educacional).',
    profit: 'Lucro historicamente volátil, seguindo o ciclo de preços da celulose no mercado internacional (exemplo educacional).',
    margin: 'Margens historicamente elevadas por ter custo de produção competitivo globalmente.',
    roe: 'ROE historicamente volátil, atingindo picos em ciclos de celulose em alta (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do setor intensivo em capital (florestas e fábricas) (exemplo educacional).',
    cashFlow: 'Forte geração de caixa em ciclos de preço de celulose favoráveis.',
    pl: 'P/L historicamente muito variável, acompanhando o ciclo de preços da celulose (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 2,5% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 51,30 (ago/2026)',
    priceValue: 51.30,
    dividendYieldValue: 2.52,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Irregular — costuma pagar quando o ciclo de celulose está favorável.',
    growth: 'Crescimento ligado à expansão de capacidade produtiva e à demanda global por celulose e papel.',
    risks: ['Preço internacional da celulose', 'Câmbio', 'Alto endividamento', 'Riscos ambientais ligados ao uso da terra'],
    outlook: 'Perspectivas ligadas à demanda global por celulose (usada em papel, embalagens e higiene) e à expansão de novas fábricas.',
    positives: ['Baixo custo de produção por ter florestas próprias no Brasil', 'Grande escala global', 'Exposição ao dólar pode beneficiar em cenários de real fraco'],
    attention: ['Resultados historicamente muito cíclicos', 'Alto endividamento exige disciplina financeira'],
    dangers: ['Queda prolongada no preço internacional da celulose', 'Riscos ambientais e regulatórios ligados ao uso de terras e florestas'],
    qualitySummary: 'Produtora de baixo custo em escala global, mas com resultados historicamente muito cíclicos.',
    priceSummary: 'Múltiplos tendem a parecer baratos no topo do ciclo de celulose e caros no fundo do ciclo.',
  },
  {
    id: 'jbs',
    name: 'JBS',
    ticker: 'JBSS3',
    sector: 'Alimentos',
    whatItDoes: 'Uma das maiores empresas de processamento de proteína animal do mundo, com operações de carne bovina, suína, de frango e produtos processados.',
    howItMakesMoney: 'Compra gado, suínos e aves, processa e vende carne e produtos derivados para o Brasil e mais de 100 países.',
    revenue: 'Receita muito elevada em volume, mas com margens historicamente apertadas, típicas do setor de proteínas (exemplo educacional).',
    profit: 'Lucro historicamente volátil, sensível ao preço do gado e das commodities agrícolas usadas na ração (exemplo educacional).',
    margin: 'Margens historicamente baixas e cíclicas, típicas do setor de processamento de carnes (exemplo educacional).',
    roe: 'ROE historicamente volátil, acompanhando o chamado "ciclo do gado" (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural de um negócio de grande escala com margens apertadas (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível ao ciclo de preços de gado, grãos e câmbio.',
    pl: 'P/L historicamente baixo, refletindo margens apertadas e alto volume de receita (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Sem dividendos pagos nos últimos 12 meses (pesquisado em ago/2026) — o último pagamento ficou fora dessa janela.',
    priceApprox: 'R$ 38,90 (ago/2026)',
    priceValue: 38.90,
    dividendYieldValue: 0,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Irregular, geralmente anual ou semestral.',
    growth: 'Crescimento ligado a aquisições internacionais e à diversificação de proteínas e produtos processados de maior valor agregado.',
    risks: ['Preço do gado e de grãos usados na ração', 'Câmbio', 'Risco sanitário (doenças animais)', 'Alto endividamento'],
    outlook: 'Perspectivas ligadas à demanda global por proteína animal e à diversificação geográfica e de produtos.',
    positives: ['Maior escala global do setor', 'Forte diversificação geográfica', 'Presença em produtos processados de maior margem'],
    attention: ['Margens historicamente apertadas e cíclicas', 'Alto endividamento'],
    dangers: ['Crises sanitárias (ex: doenças em rebanhos)', 'Barreiras comerciais e sanitárias à exportação', 'Questões ambientais ligadas à pecuária'],
    qualitySummary: 'Maior escala global do setor de proteínas, mas com margens historicamente apertadas e resultado cíclico.',
    priceSummary: 'Costuma negociar com múltiplos baixos, refletindo as margens historicamente apertadas do setor.',
  },
  {
    id: 'rede-dor',
    name: "Rede D'Or",
    ticker: 'RDOR3',
    sector: 'Saúde',
    whatItDoes: 'Maior rede de hospitais privados do Brasil, com atuação também em planos de saúde e diagnósticos.',
    howItMakesMoney: 'Cobra por procedimentos, internações e serviços hospitalares, seja diretamente ou através de convênios com planos de saúde.',
    revenue: 'Receita em crescimento consistente, impulsionada por aquisições de hospitais e aumento de procedimentos (exemplo educacional).',
    profit: 'Lucro em crescimento, mas sensível ao custo de pessoal e insumos médicos (exemplo educacional).',
    margin: 'Margens historicamente saudáveis para o setor hospitalar (exemplo educacional).',
    roe: 'ROE historicamente moderado, típico de um setor intensivo em capital (hospitais) (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural de um setor que cresce por aquisições de hospitais (exemplo educacional).',
    cashFlow: 'Geração de caixa operacional consistente, sustentando novos investimentos e aquisições.',
    pl: 'P/L historicamente elevado, refletindo a expectativa de crescimento do setor de saúde privada (exemplo educacional).',
    pvp: 'P/VP historicamente elevado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 12,6% ao ano nos últimos 12 meses (pesquisado em ago/2026) — bem acima do padrão histórico da empresa, vale conferir de novo mais à frente.',
    priceApprox: 'R$ 32,60 (ago/2026)',
    priceValue: 32.60,
    dividendYieldValue: 12.59,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral (pagamentos observados em abr/jul/out/dez).',
    growth: 'Crescimento historicamente forte, via aquisição de novos hospitais e aumento de leitos.',
    risks: ['Alto custo de pessoal médico e insumos hospitalares', 'Endividamento ligado a aquisições', 'Regulação do setor de saúde'],
    outlook: 'Perspectivas ligadas ao envelhecimento da população e à expansão da rede de hospitais e planos de saúde.',
    positives: ['Maior rede hospitalar privada do país', 'Crescimento consistente via aquisições', 'Presença em regiões de alta renda'],
    attention: ['Valuation historicamente exigente (P/L alto)', 'Endividamento ligado ao ritmo de aquisições'],
    dangers: ['Custos médicos podem crescer mais rápido que os reajustes de convênios', 'Mudanças regulatórias no setor de saúde suplementar'],
    qualitySummary: 'Líder consolidado no setor hospitalar privado brasileiro, com forte histórico de crescimento.',
    priceSummary: 'Costuma negociar com múltiplos mais altos, refletindo a expectativa de crescimento do setor de saúde privada.',
  },
  {
    id: 'hapvida',
    name: 'Hapvida',
    ticker: 'HAPV3',
    sector: 'Saúde',
    whatItDoes: 'Uma das maiores operadoras de planos de saúde do Brasil, com modelo verticalizado (própria rede de hospitais e clínicas).',
    howItMakesMoney: 'Cobra mensalidades de planos de saúde e usa sua própria rede de hospitais e clínicas para atender os beneficiários, controlando custos.',
    revenue: 'Receita em crescimento, impulsionada pelo aumento de beneficiários e aquisições de outras operadoras (exemplo educacional).',
    profit: 'Lucro historicamente pressionado pela integração de aquisições e pela sinistralidade (uso dos planos) (exemplo educacional).',
    margin: 'Margens historicamente sensíveis ao nível de sinistralidade (quanto os beneficiários usam o plano) (exemplo educacional).',
    roe: 'ROE historicamente volátil, refletindo o processo de integração de grandes aquisições (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, ampliado por aquisições relevantes no setor (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível à sinistralidade e à integração de operações adquiridas.',
    pl: 'P/L historicamente muito variável durante o processo de integração de aquisições (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Sem dividendos pagos nos últimos 12 meses (pesquisado em ago/2026) — a empresa não distribui desde jan/2022.',
    priceApprox: 'R$ 4,15 (ago/2026)',
    priceValue: 4.15,
    dividendYieldValue: 0,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Irregular, historicamente modesto.',
    growth: 'Crescimento historicamente forte via aquisições, com foco atual em integração e redução de custos.',
    risks: ['Sinistralidade (uso excessivo dos planos)', 'Endividamento ligado a aquisições', 'Regulação da ANS (Agência Nacional de Saúde Suplementar)'],
    outlook: 'Perspectivas ligadas à conclusão da integração das aquisições e à melhora da rentabilidade do modelo verticalizado.',
    positives: ['Modelo verticalizado ajuda a controlar custos no longo prazo', 'Grande base de beneficiários', 'Presença forte fora dos grandes centros'],
    attention: ['Processo de integração de aquisições ainda em andamento', 'Rentabilidade historicamente instável'],
    dangers: ['Sinistralidade acima do esperado pode pressionar fortemente os resultados', 'Regulação mais rígida sobre planos de saúde'],
    qualitySummary: 'Modelo de negócio diferenciado (verticalizado), mas com histórico recente de rentabilidade instável.',
    priceSummary: 'Historicamente volátil, com múltiplos sensíveis às expectativas de melhora de rentabilidade.',
  },
  {
    id: 'cosan',
    name: 'Cosan',
    ticker: 'CSAN3',
    sector: 'Energia e combustíveis',
    whatItDoes: 'Holding com participações em distribuição de combustíveis (Raízen), açúcar e etanol, gás natural e outros negócios de energia.',
    howItMakesMoney: 'Ganha através dos resultados de suas empresas controladas e coligadas, principalmente ligadas a energia, combustíveis e açúcar/etanol.',
    revenue: 'Receita consolidada elevada, refletindo o porte das empresas do grupo (exemplo educacional).',
    profit: 'Lucro historicamente volátil, dependente do resultado das controladas e de itens não recorrentes (exemplo educacional).',
    margin: 'Margens variam bastante entre os diferentes negócios do grupo (exemplo educacional).',
    roe: 'ROE historicamente volátil, refletindo a estrutura de holding com múltiplos negócios (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, tanto na holding quanto nas controladas (exemplo educacional).',
    cashFlow: 'Geração de caixa dependente do desempenho combinado das empresas do grupo.',
    pl: 'P/L historicamente muito variável, sensível a eventos não recorrentes (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Sem dividendos pagos nos últimos 12 meses (pesquisado em ago/2026) — o último pagamento ficou fora dessa janela.',
    priceApprox: 'R$ 11,70 (ago/2026)',
    priceValue: 11.70,
    dividendYieldValue: 0,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Anual, com valores historicamente variáveis.',
    growth: 'Crescimento ligado à expansão dos negócios de energia, combustíveis e gás natural do grupo.',
    risks: ['Complexidade da estrutura societária (holding com várias controladas)', 'Alto endividamento', 'Exposição a preços de commodities (açúcar, etanol, combustíveis)'],
    outlook: 'Perspectivas ligadas à transição energética e à expansão dos negócios de gás natural e biocombustíveis.',
    positives: ['Presença em negócios essenciais de energia e combustíveis', 'Diversificação entre diferentes setores', 'Grande escala operacional'],
    attention: ['Estrutura societária complexa dificulta a análise', 'Resultados sensíveis a itens não recorrentes'],
    dangers: ['Alto endividamento consolidado', 'Ciclos de preço de commodities agrícolas e energéticas'],
    qualitySummary: 'Holding diversificada em energia, com negócios relevantes mas estrutura societária complexa.',
    priceSummary: 'Costuma ser avaliada pela soma das partes (valor das empresas controladas), o que exige análise mais detalhada.',
  },
  {
    id: 'gerdau',
    name: 'Gerdau',
    ticker: 'GGBR4',
    sector: 'Siderurgia',
    whatItDoes: 'Uma das maiores produtoras de aço das Américas, com operações no Brasil, Estados Unidos e outros países.',
    howItMakesMoney: 'Produz e vende aço para construção civil, indústria automotiva e outros setores, no Brasil e no exterior.',
    revenue: 'Receita fortemente ligada ao consumo de aço na construção civil e na indústria (exemplo educacional).',
    profit: 'Lucro historicamente cíclico, acompanhando a demanda por aço e o preço do minério de ferro (matéria-prima) (exemplo educacional).',
    margin: 'Margens historicamente cíclicas, típicas do setor siderúrgico (exemplo educacional).',
    roe: 'ROE historicamente volátil, atingindo picos em ciclos de aço em alta (exemplo educacional).',
    debt: 'Endividamento historicamente moderado, com melhora nos últimos anos (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível ao ciclo de preços do aço e ao nível de atividade da construção civil.',
    pl: 'P/L historicamente baixo em momentos de ciclo de aço fraco (exemplo educacional).',
    pvp: 'P/VP historicamente baixo a moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 3,0% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 18,40 (ago/2026)',
    priceValue: 18.40,
    dividendYieldValue: 3.04,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral (pagamentos observados em mar/mai/ago/nov-dez).',
    growth: 'Crescimento ligado à demanda por aço na construção civil, infraestrutura e indústria automotiva.',
    risks: ['Ciclo de preços do aço', 'Concorrência de aço importado (especialmente da China)', 'Custo de matérias-primas'],
    outlook: 'Perspectivas ligadas a investimentos em infraestrutura no Brasil e nos EUA, e à demanda da construção civil.',
    positives: ['Diversificação geográfica (Brasil e EUA)', 'Marca consolidada no setor siderúrgico', 'Histórico de disciplina de capital'],
    attention: ['Resultados historicamente cíclicos', 'Concorrência de aço importado a preços mais baixos'],
    dangers: ['Entrada maciça de aço importado a preços de dumping', 'Desaceleração da construção civil e da indústria'],
    qualitySummary: 'Produtora consolidada de aço, com diversificação geográfica, mas resultado historicamente cíclico.',
    priceSummary: 'Múltiplos tendem a parecer baixos no fundo do ciclo do aço, o que pode enganar quem olha só o P/L momentâneo.',
  },
  {
    id: 'csn',
    name: 'CSN',
    ticker: 'CSNA3',
    sector: 'Siderurgia e mineração',
    whatItDoes: 'Empresa siderúrgica e de mineração, com operações também em cimento, energia e logística.',
    howItMakesMoney: 'Produz e vende aço e minério de ferro, além de cimento, com receita diversificada entre esses negócios.',
    revenue: 'Receita diversificada entre siderurgia, mineração e cimento, com peso relevante do minério de ferro (exemplo educacional).',
    profit: 'Lucro historicamente muito volátil, sensível ao preço do minério de ferro e do aço (exemplo educacional).',
    margin: 'Margens historicamente cíclicas, variando bastante entre os diferentes negócios do grupo (exemplo educacional).',
    roe: 'ROE historicamente volátil, refletindo a natureza cíclica dos negócios (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, um dos pontos mais observados pelo mercado (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível ao ciclo de preços de minério de ferro e aço.',
    pl: 'P/L historicamente muito variável, acompanhando o ciclo de commodities (exemplo educacional).',
    pvp: 'P/VP historicamente baixo a moderado (exemplo educacional).',
    dividendYield: 'Sem dividendos pagos nos últimos 12 meses (pesquisado em ago/2026) — o último pagamento ficou fora dessa janela.',
    priceApprox: 'R$ 13,10 (ago/2026)',
    priceValue: 13.10,
    dividendYieldValue: 0,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral, com valores muito variáveis conforme o ciclo.',
    growth: 'Crescimento ligado à expansão da produção de minério de ferro e à demanda por aço e cimento.',
    risks: ['Alto endividamento', 'Ciclo de preços de minério de ferro e aço', 'Complexidade do grupo (vários negócios diferentes)'],
    outlook: 'Perspectivas ligadas à demanda global por minério de ferro e aço, e à disciplina de capital do grupo.',
    positives: ['Diversificação entre mineração, siderurgia e cimento', 'Ativos de minério de ferro de boa qualidade', 'Presença consolidada no Brasil'],
    attention: ['Endividamento historicamente elevado é um ponto de atenção recorrente', 'Resultados muito sensíveis a ciclos de commodities'],
    dangers: ['Queda simultânea no preço de minério e aço', 'Nível de endividamento em cenários de juros altos'],
    qualitySummary: 'Grupo diversificado em commodities, mas com endividamento historicamente elevado e resultados muito cíclicos.',
    priceSummary: 'Costuma negociar com múltiplos baixos, refletindo o risco de alavancagem e a natureza cíclica do negócio.',
  },
  {
    id: 'klabin',
    name: 'Klabin',
    ticker: 'KLBN11',
    sector: 'Papel e celulose',
    whatItDoes: 'Maior produtora e exportadora de papéis do Brasil, com atuação também em celulose e embalagens.',
    howItMakesMoney: 'Vende papel, celulose e embalagens para clientes no Brasil e no exterior, com florestas próprias de eucalipto e pinus.',
    revenue: 'Receita diversificada entre papel, celulose e embalagens, com parte relevante em exportação (exemplo educacional).',
    profit: 'Lucro historicamente menos volátil que produtoras puras de celulose, por ter negócio diversificado (exemplo educacional).',
    margin: 'Margens historicamente saudáveis, beneficiadas pela integração florestal (exemplo educacional).',
    roe: 'ROE historicamente moderado (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do setor intensivo em capital (florestas e fábricas) (exemplo educacional).',
    cashFlow: 'Geração de caixa historicamente mais estável que produtoras puras de celulose, por ter receita diversificada.',
    pl: 'P/L historicamente moderado (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 6,4% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 21,60 (ago/2026)',
    priceValue: 21.60,
    dividendYieldValue: 6.43,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral.',
    growth: 'Crescimento ligado à expansão de capacidade de celulose e embalagens, e à demanda por papel para embalagens (impulsionada pelo e-commerce).',
    risks: ['Preço internacional da celulose', 'Câmbio', 'Alto endividamento', 'Riscos ambientais ligados ao uso da terra'],
    outlook: 'Perspectivas ligadas à demanda por embalagens de papel (favorecida pelo e-commerce) e à expansão de novas fábricas.',
    positives: ['Negócio diversificado entre papel, celulose e embalagens', 'Florestas próprias reduzem custo de matéria-prima', 'Demanda por embalagens de papel em crescimento estrutural'],
    attention: ['Endividamento elevado exige disciplina financeira', 'Ainda exposta ao ciclo de preços da celulose'],
    dangers: ['Queda prolongada no preço internacional da celulose', 'Riscos ambientais e regulatórios ligados a florestas'],
    qualitySummary: 'Negócio diversificado e com integração florestal, historicamente menos cíclico que produtoras puras de celulose.',
    priceSummary: 'Costuma negociar com múltiplos um pouco mais estáveis que pares mais dependentes só da celulose.',
  },
  {
    id: 'ultrapar',
    name: 'Ultrapar',
    ticker: 'UGPA3',
    sector: 'Distribuição de combustíveis',
    whatItDoes: 'Dona da rede de postos Ipiranga, uma das maiores distribuidoras de combustíveis do Brasil, além de outros negócios como a Ultragaz.',
    howItMakesMoney: 'Distribui combustíveis para postos de gasolina (rede Ipiranga) e vende gás liquefeito de petróleo (GLP) através da Ultragaz.',
    revenue: 'Receita elevada em volume, mas com margens historicamente apertadas, típicas de distribuição de combustíveis (exemplo educacional).',
    profit: 'Lucro historicamente sensível à regulação de preços de combustíveis e à concorrência do setor (exemplo educacional).',
    margin: 'Margens historicamente baixas por litro, compensadas pelo grande volume vendido (exemplo educacional).',
    roe: 'ROE historicamente moderado (exemplo educacional).',
    debt: 'Endividamento historicamente moderado (exemplo educacional).',
    cashFlow: 'Geração de caixa relativamente previsível, ligada ao consumo de combustíveis no Brasil.',
    pl: 'P/L historicamente moderado (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 3,8% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 19,80 (ago/2026)',
    priceValue: 19.80,
    dividendYieldValue: 3.76,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral.',
    growth: 'Crescimento ligado ao consumo de combustíveis e à expansão da rede de postos e revendas.',
    risks: ['Política de preços de combustíveis da Petrobras', 'Concorrência de outras distribuidoras', 'Regulação do setor de combustíveis'],
    outlook: 'Perspectivas ligadas ao crescimento da frota de veículos no Brasil e à expansão de serviços dentro dos postos.',
    positives: ['Marca forte e rede consolidada de postos', 'Negócio essencial e relativamente previsível', 'Diversificação com Ultragaz'],
    attention: ['Margens historicamente apertadas', 'Sensível a mudanças na política de preços de combustíveis'],
    dangers: ['Guerra de preços entre distribuidoras', 'Mudanças regulatórias no setor de combustíveis'],
    qualitySummary: 'Negócio essencial e consolidado, com margens historicamente apertadas mas operação relativamente previsível.',
    priceSummary: 'Costuma ser avaliada mais pela previsibilidade do negócio do que por potencial de crescimento acelerado.',
  },
  {
    id: 'raia-drogasil',
    name: 'Raia Drogasil',
    ticker: 'RADL3',
    sector: 'Varejo farmacêutico',
    whatItDoes: 'Maior rede de farmácias do Brasil, dona das marcas Droga Raia e Drogasil.',
    howItMakesMoney: 'Vende medicamentos e produtos de higiene, beleza e conveniência através de suas lojas físicas e canais digitais.',
    revenue: 'Receita em crescimento consistente, impulsionada pela abertura de novas lojas (exemplo educacional).',
    profit: 'Lucro em crescimento consistente, acompanhando a expansão da rede de lojas (exemplo educacional).',
    margin: 'Margens historicamente estáveis, típicas do varejo farmacêutico (exemplo educacional).',
    roe: 'ROE historicamente elevado e consistente, um destaque do varejo brasileiro (exemplo educacional).',
    debt: 'Endividamento historicamente baixo a moderado (exemplo educacional).',
    cashFlow: 'Boa geração de caixa operacional, sustentando a abertura de novas lojas.',
    pl: 'P/L historicamente elevado, refletindo a percepção de qualidade e crescimento consistente (exemplo educacional).',
    pvp: 'P/VP historicamente elevado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 2,5% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 5,60 (ago/2026)',
    priceValue: 5.60,
    dividendYieldValue: 2.51,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Anual, com valores historicamente modestos.',
    growth: 'Crescimento historicamente forte e consistente, via abertura de novas lojas e ganho de participação de mercado.',
    risks: ['Valuation historicamente exigente (P/L alto)', 'Concorrência de outras redes de farmácia e e-commerce', 'Regulação de preços de medicamentos'],
    outlook: 'Perspectivas ligadas à continuidade da expansão de lojas e ao aumento de participação de mercado no varejo farmacêutico fragmentado.',
    positives: ['Histórico consistente de crescimento e execução', 'Alta rentabilidade (ROE)', 'Setor relativamente defensivo (saúde e bem-estar)'],
    attention: ['Valuation historicamente exigente frente à média do mercado', 'Crescimento depende de continuar abrindo lojas com sucesso'],
    dangers: ['Pagar caro demais por uma empresa boa é, ainda assim, um risco de valuation', 'Saturação de mercado em praças já muito atendidas'],
    qualitySummary: 'Uma das varejistas mais bem avaliadas da bolsa brasileira, com histórico consistente de execução.',
    priceSummary: 'Costuma negociar com múltiplos mais altos que a média do varejo, refletindo a qualidade percebida do negócio.',
  },
  {
    id: 'renner',
    name: 'Lojas Renner',
    ticker: 'LREN3',
    sector: 'Varejo de moda',
    whatItDoes: 'Maior rede de lojas de moda do Brasil, com marcas próprias de vestuário e também serviços financeiros (cartão Renner).',
    howItMakesMoney: 'Vende roupas e acessórios em lojas físicas e e-commerce, além de gerar receita com seu cartão de crédito próprio.',
    revenue: 'Receita ligada ao consumo de vestuário e ao desempenho do cartão de crédito próprio (exemplo educacional).',
    profit: 'Lucro historicamente sensível ao nível de consumo das famílias e a juros altos (exemplo educacional).',
    margin: 'Margens historicamente saudáveis para o varejo de moda (exemplo educacional).',
    roe: 'ROE historicamente elevado, um dos destaques do varejo brasileiro em períodos normais (exemplo educacional).',
    debt: 'Endividamento historicamente moderado (exemplo educacional).',
    cashFlow: 'Geração de caixa sensível à sazonalidade do varejo de moda (datas comemorativas, trocas de estação).',
    pl: 'P/L historicamente moderado a elevado, variando com o ciclo de consumo (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 8,5% ao ano nos últimos 12 meses (pesquisado em ago/2026) — acima do padrão histórico da empresa.',
    priceApprox: 'R$ 14,90 (ago/2026)',
    priceValue: 14.90,
    dividendYieldValue: 8.45,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral (pagamentos observados em jan/abr/jul/out).',
    growth: 'Crescimento ligado à expansão de lojas, ao e-commerce e ao desempenho do cartão de crédito próprio.',
    risks: ['Sensibilidade a juros altos (afeta consumo e o cartão próprio)', 'Concorrência de fast fashion internacional e e-commerce chinês', 'Inadimplência no cartão próprio'],
    outlook: 'Perspectivas ligadas à recuperação do consumo das famílias e à integração entre loja física e digital.',
    positives: ['Marca forte e consolidada no varejo de moda', 'Operação de cartão de crédito complementa a receita', 'Histórico de boa execução operacional'],
    attention: ['Resultado sensível ao nível de juros e consumo', 'Concorrência crescente de e-commerce internacional de baixo custo'],
    dangers: ['Alta inadimplência no cartão de crédito próprio em cenários de juros altos', 'Concorrência agressiva de plataformas internacionais de moda'],
    qualitySummary: 'Uma das varejistas de moda mais bem avaliadas do país, mas sensível ao ciclo de consumo e juros.',
    priceSummary: 'Múltiplos costumam variar bastante conforme as expectativas para o consumo das famílias.',
  },
  {
    id: 'natura',
    name: 'Natura &Co',
    ticker: 'NTCO3',
    sector: 'Cosméticos',
    whatItDoes: 'Empresa brasileira de cosméticos e produtos de beleza, dona das marcas Natura e Avon, com venda direta e lojas físicas.',
    howItMakesMoney: 'Vende cosméticos e produtos de beleza através de consultoras (venda direta), lojas físicas e canais digitais.',
    revenue: 'Receita historicamente pressionada pela integração da Avon e pela reestruturação do negócio internacional (exemplo educacional).',
    profit: 'Lucro historicamente volátil, incluindo períodos de prejuízo durante a reestruturação (exemplo educacional).',
    margin: 'Margens historicamente pressionadas pelos custos de reestruturação e integração da Avon (exemplo educacional).',
    roe: 'ROE historicamente baixo ou negativo nos últimos anos, refletindo o período de reestruturação (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, ampliado pela aquisição da Avon (exemplo educacional).',
    cashFlow: 'Geração de caixa historicamente pressionada durante o processo de reestruturação e venda de ativos internacionais.',
    pl: 'P/L historicamente pouco relevante em anos de prejuízo — deve ser analisado com cautela (exemplo educacional).',
    pvp: 'P/VP historicamente baixo, refletindo o período de dificuldade (exemplo educacional).',
    dividendYield: 'Dividend Yield efetivamente ≈ 0% nos últimos 12 meses (pesquisado em ago/2026) — a empresa pagou dividendos no período, mas a queda de ~22% no preço da ação zerou o cálculo do yield.',
    priceApprox: 'R$ 16,30 (ago/2026)',
    priceValue: 16.30,
    dividendYieldValue: 0,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Irregular, historicamente modesto ou ausente.',
    growth: 'Crescimento futuro depende da conclusão da reestruturação e do foco nas marcas Natura e Avon na América Latina.',
    risks: ['Processo de reestruturação ainda em andamento', 'Alto endividamento', 'Concorrência de outras marcas de cosméticos e canais de venda direta'],
    outlook: 'Perspectivas ligadas à simplificação do negócio (venda de operações internacionais) e ao foco na América Latina.',
    positives: ['Marcas fortes e reconhecidas (Natura, Avon)', 'Modelo de venda direta com grande rede de consultoras', 'Posicionamento de sustentabilidade consolidado'],
    attention: ['Histórico recente de prejuízos e reestruturação', 'Endividamento ainda elevado'],
    dangers: ['Reestruturação pode não entregar os resultados esperados', 'Concorrência de canais digitais de beleza de baixo custo'],
    qualitySummary: 'Marcas fortes em processo de reestruturação, com histórico recente de resultados fracos.',
    priceSummary: 'Historicamente volátil, com múltiplos sensíveis ao progresso da reestruturação e redução de dívida.',
  },
  {
    id: 'equatorial',
    name: 'Equatorial Energia',
    ticker: 'EQTL3',
    sector: 'Energia elétrica',
    whatItDoes: 'Grupo de energia elétrica com atuação em distribuição, transmissão, geração e saneamento em diversos estados brasileiros.',
    howItMakesMoney: 'Distribui energia elétrica para consumidores finais (com tarifas reguladas) e também atua em transmissão, geração e saneamento.',
    revenue: 'Receita previsível, sustentada por contratos regulados de distribuição e transmissão de energia (exemplo educacional).',
    profit: 'Lucro em crescimento consistente, impulsionado por aquisições de distribuidoras e ganhos de eficiência (exemplo educacional).',
    margin: 'Margens historicamente saudáveis, melhoradas por ganhos de eficiência em distribuidoras adquiridas (exemplo educacional).',
    roe: 'ROE historicamente elevado para o setor de utilities (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural de um setor intensivo em capital e de crescimento por aquisições (exemplo educacional).',
    cashFlow: 'Geração de caixa previsível, sustentando novos investimentos e aquisições.',
    pl: 'P/L historicamente moderado a elevado, refletindo a percepção de qualidade da gestão (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 5,4% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 33,20 (ago/2026)',
    priceValue: 33.20,
    dividendYieldValue: 5.42,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Semestral.',
    growth: 'Crescimento historicamente forte, via aquisição de distribuidoras de energia em dificuldade e recuperação de sua eficiência.',
    risks: ['Regulação do setor elétrico (revisões tarifárias)', 'Endividamento ligado a aquisições', 'Condições hidrológicas afetando geração'],
    outlook: 'Perspectivas ligadas à continuidade das aquisições e turnarounds de distribuidoras, e à expansão em transmissão e saneamento.',
    positives: ['Histórico consistente de bons turnarounds de distribuidoras adquiridas', 'Diversificação entre distribuição, transmissão, geração e saneamento', 'Gestão bem avaliada pelo mercado'],
    attention: ['Endividamento elevado exige disciplina financeira', 'Crescimento depende de continuar encontrando boas aquisições'],
    dangers: ['Mudanças regulatórias que reduzam a rentabilidade da distribuição', 'Integração malsucedida de novas aquisições'],
    qualitySummary: 'Um dos grupos de energia mais bem avaliados do país, com histórico forte de execução em aquisições.',
    priceSummary: 'Costuma negociar com múltiplos mais altos que outras utilities, refletindo a qualidade percebida da gestão.',
  },
  {
    id: 'cpfl',
    name: 'CPFL Energia',
    ticker: 'CPFE3',
    sector: 'Energia elétrica',
    whatItDoes: 'Grupo de energia elétrica com atuação em distribuição, geração (incluindo renováveis) e comercialização de energia, principalmente no estado de São Paulo.',
    howItMakesMoney: 'Distribui energia elétrica para consumidores finais com tarifas reguladas, e também gera e comercializa energia.',
    revenue: 'Receita previsível, sustentada por contratos regulados de distribuição e venda de energia (exemplo educacional).',
    profit: 'Lucro estável e previsível, típico de empresas do setor elétrico (exemplo educacional).',
    margin: 'Margens historicamente elevadas e estáveis (exemplo educacional).',
    roe: 'ROE historicamente sólido para o setor de utilities (exemplo educacional).',
    debt: 'Endividamento historicamente moderado a elevado, comum no setor por ser intensivo em capital (exemplo educacional).',
    cashFlow: 'Geração de caixa previsível, sustentando uma política de dividendos consistente.',
    pl: 'P/L historicamente moderado, condizente com um setor de baixo crescimento e alta previsibilidade (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 8,8% ao ano nos últimos 12 meses (pesquisado em ago/2026).',
    priceApprox: 'R$ 39,50 (ago/2026)',
    priceValue: 39.50,
    dividendYieldValue: 8.79,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Trimestral.',
    growth: 'Crescimento moderado, ligado a novos projetos de geração renovável e leilões de energia e transmissão.',
    risks: ['Regulação do setor elétrico', 'Renovação de concessões de distribuição', 'Condições hidrológicas afetando a geração'],
    outlook: 'Perspectivas ligadas à expansão de energias renováveis e à demanda de energia na região Sudeste.',
    positives: ['Receita previsível via distribuição regulada', 'Bom histórico de dividendos', 'Presença consolidada em São Paulo, região de alta renda'],
    attention: ['Crescimento historicamente mais lento que setores cíclicos', 'Depende de renovação de concessões e leilões'],
    dangers: ['Mudanças regulatórias podem afetar contratos e tarifas de distribuição'],
    qualitySummary: 'Empresa historicamente considerada defensiva, com receitas previsíveis e bom histórico de dividendos.',
    priceSummary: 'Costuma ser avaliada mais pelo Dividend Yield e previsibilidade do que por potencial de crescimento acelerado.',
  },
  {
    id: 'sabesp',
    name: 'Sabesp',
    ticker: 'SBSP3',
    sector: 'Saneamento',
    whatItDoes: 'Maior companhia de saneamento básico do Brasil, responsável pelo fornecimento de água e coleta de esgoto no estado de São Paulo, recentemente privatizada.',
    howItMakesMoney: 'Cobra tarifas reguladas de água e esgoto de residências e empresas, com contratos de concessão de longo prazo.',
    revenue: 'Receita previsível, sustentada por tarifas reguladas de água e esgoto (exemplo educacional).',
    profit: 'Lucro em melhora após a privatização, com foco em eficiência operacional (exemplo educacional).',
    margin: 'Margens em processo de melhora, com metas de eficiência definidas após a privatização (exemplo educacional).',
    roe: 'ROE em recuperação, com metas de rentabilidade mais altas estabelecidas pelo novo controle privado (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do setor de saneamento, intensivo em capital (exemplo educacional).',
    cashFlow: 'Geração de caixa previsível, sustentando investimentos em expansão de rede de água e esgoto.',
    pl: 'P/L historicamente moderado, com expectativa de melhora após a privatização (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 3,0% ao ano nos últimos 12 meses (pesquisado em ago/2026), com expectativa de crescimento.',
    priceApprox: 'R$ 106,80 (ago/2026)',
    priceValue: 106.80,
    dividendYieldValue: 2.97,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Anual, com política de dividendos em revisão após a privatização.',
    growth: 'Crescimento ligado às metas de universalização do saneamento (água e esgoto) definidas pelo marco regulatório do setor.',
    risks: ['Execução do plano de eficiência pós-privatização', 'Regulação tarifária', 'Investimentos elevados necessários para universalizar o saneamento'],
    outlook: 'Perspectivas ligadas ao cumprimento das metas de universalização do saneamento em São Paulo até 2029/2033.',
    positives: ['Monopólio natural em uma região de alta renda (São Paulo)', 'Metas regulatórias claras de universalização', 'Nova gestão privada com foco em eficiência'],
    attention: ['Execução do plano de investimentos e eficiência ainda em fase inicial', 'Endividamento elevado para financiar expansão'],
    dangers: ['Não cumprir metas de universalização pode gerar penalidades regulatórias', 'Mudanças no marco regulatório do saneamento'],
    qualitySummary: 'Monopólio essencial em processo de melhora de eficiência após a privatização, com metas regulatórias claras.',
    priceSummary: 'Costuma ser avaliada pela expectativa de melhora de eficiência e crescimento de dividendos pós-privatização.',
  },
  {
    id: 'eletrobras',
    name: 'Axia Energia (ex-Eletrobras)',
    ticker: 'AXIA3',
    sector: 'Energia elétrica',
    whatItDoes: 'Maior empresa de energia elétrica da América Latina, com atuação em geração (principalmente hidrelétrica) e transmissão. Renomeada de Eletrobras para Axia Energia em 10/nov/2025, com o ticker mudando de ELET3 para AXIA3.',
    howItMakesMoney: 'Gera e transmite energia elétrica, vendendo para distribuidoras e grandes consumidores através de contratos regulados e no mercado livre.',
    revenue: 'Receita elevada, sustentada por contratos de venda de energia de longo prazo (exemplo educacional).',
    profit: 'Lucro em processo de normalização após a privatização, com foco em redução de custos (exemplo educacional).',
    margin: 'Margens em melhora, com metas de eficiência definidas após a privatização (exemplo educacional).',
    roe: 'ROE historicamente baixo quando estatal, em processo de melhora sob controle privado (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do setor de geração e transmissão, intensivo em capital (exemplo educacional).',
    cashFlow: 'Geração de caixa em melhora, sustentando redução de dívida e novos investimentos.',
    pl: 'P/L historicamente pouco comparável devido a itens não recorrentes ligados à privatização (exemplo educacional).',
    pvp: 'P/VP historicamente moderado (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 3,7% ao ano nos últimos 12 meses (pesquisado em ago/2026, já sob o ticker AXIA3).',
    priceApprox: 'R$ 59,50 (ago/2026)',
    priceValue: 59.50,
    dividendYieldValue: 3.69,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Anual, com política de dividendos em consolidação após a privatização.',
    growth: 'Crescimento ligado à melhora de eficiência operacional e à expansão em energias renováveis e transmissão.',
    risks: ['Execução do plano de eficiência pós-privatização', 'Regulação do setor elétrico', 'Condições hidrológicas (a maior parte da geração é hidrelétrica)'],
    outlook: 'Perspectivas ligadas à conclusão do processo de turnaround e à modernização da maior geradora de energia do país.',
    positives: ['Maior parque gerador de energia da América Latina', 'Matriz predominantemente renovável (hidrelétrica)', 'Potencial de ganho de eficiência sob gestão privada'],
    attention: ['Processo de turnaround pós-privatização ainda em andamento', 'Resultados históricos pouco comparáveis por itens não recorrentes'],
    dangers: ['Turnaround pode demorar mais que o esperado pelo mercado', 'Condições hidrológicas desfavoráveis (períodos de seca)'],
    qualitySummary: 'Maior geradora de energia da América Latina, em processo de melhora de eficiência após a privatização.',
    priceSummary: 'Costuma ser avaliada pela expectativa de ganho de eficiência e redução de custos sob a nova gestão privada.',
  },
  {
    id: 'cemig',
    name: 'Cemig',
    ticker: 'CMIG4',
    sector: 'Energia elétrica',
    whatItDoes: 'Companhia Energética de Minas Gerais — grupo de energia elétrica com atuação em distribuição, geração (hidrelétrica majoritariamente) e transmissão, controlada pelo governo do estado de Minas Gerais.',
    howItMakesMoney: 'Distribui energia elétrica com tarifas reguladas para consumidores de Minas Gerais, e também gera e transmite energia através de contratos regulados e no mercado livre.',
    revenue: 'Receita previsível, sustentada por tarifas reguladas de distribuição e contratos de venda de energia (exemplo educacional).',
    profit: 'Lucro historicamente volátil ano a ano, sensível a decisões regulatórias e disputas judiciais (exemplo educacional).',
    margin: 'Margens historicamente medianas para o setor elétrico, variando com o resultado de geração (exemplo educacional).',
    roe: 'ROE historicamente volátil, afetado por itens não recorrentes e por ser controlada por um ente estatal (exemplo educacional).',
    debt: 'Endividamento historicamente elevado, natural do setor de distribuição/geração, intensivo em capital (exemplo educacional).',
    cashFlow: 'Geração de caixa historicamente forte na distribuição, sustentando uma política de dividendos generosa.',
    pl: 'P/L historicamente baixo em relação à média do mercado, refletindo o desconto por ser uma estatal (exemplo educacional).',
    pvp: 'P/VP historicamente baixo (exemplo educacional).',
    dividendYield: 'Dividend Yield ≈ 8,2% ao ano nos últimos 12 meses (pesquisado em ago/2026) — historicamente um dos maiores pagadores do setor elétrico, embora o valor varie bastante ano a ano.',
    priceApprox: 'R$ 10,12 (ago/2026)',
    priceValue: 10.12,
    dividendYieldValue: 8.15,
    dividendReferenceMonth: '2026-08',
    payoutFrequency: 'Semestral (historicamente junho e dezembro), com valor variável ano a ano.',
    growth: 'Crescimento moderado, ligado a investimentos em modernização da rede de distribuição e expansão em geração renovável.',
    risks: ['Controle estatal (governo de Minas Gerais) pode influenciar decisões de payout e gestão', 'Regulação do setor elétrico', 'Disputas judiciais e regulatórias recorrentes'],
    outlook: 'Perspectivas ligadas à execução do plano de investimentos em distribuição e a especulações recorrentes (não concretizadas) sobre privatização.',
    positives: ['Histórico de dividendos elevados', 'Forte presença de distribuição em Minas Gerais', 'Negociada com múltiplos historicamente baixos'],
    attention: ['Controle estatal traz incerteza sobre política de dividendos e governança', 'Resultado historicamente volátil ano a ano'],
    dangers: ['Interferência política em decisões da empresa, por ser controlada pelo estado de Minas Gerais', 'Mudanças regulatórias podem afetar tarifas e contratos'],
    qualitySummary: 'Distribuidora estatal historicamente conhecida por pagar dividendos elevados, mas com governança sujeita a influência política.',
    priceSummary: 'Costuma negociar com múltiplos baixos e Dividend Yield alto, refletindo o desconto de ser controlada por um ente estatal.',
  },
]
